### Import module

In [1]:
import torch

### Gradient

In [12]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
z = y*y*2
z = z.mean()  # loss function
print(z)

z.backward()  # 自動計算 z 對於所有 requires_grad=True 的變數的梯度 dz/dx
print(x.grad)

tensor([-0.2152,  0.4240,  0.3633], requires_grad=True)
tensor(9.7642, grad_fn=<MeanBackward0>)
tensor([2.3797, 3.2320, 3.1511])


### Parameter updates that without involve the model (remove gradient_fn)

In [17]:
x = torch.randn(3, requires_grad=True)
print(x)

# 1.
# x.requires_grad_(False)
# print(x)

# 2.
# y = x.detach()
# print(y)

# 3.
with torch.no_grad():
    y = x+2
    print(y)

tensor([ 1.1006, -1.3780,  0.1235], requires_grad=True)
tensor([3.1006, 0.6220, 2.1235])


In [20]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)
    
    #以便在下一個 epoch 中重新計算新的梯度。這是因為 PyTorch 默認會將計算的梯度累加在一起，所以在每個 epoch 開始之前，我們需要將梯度歸零。
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
