### Import module

In [1]:
import torch

### Gradient

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
print(y)
z = y*y*2
z = z.mean()  # loss function
print(z)

z.backward()  # 自動計算 z 對於所有 requires_grad=True 的變數的梯度 dz/dx
print(x.grad)

tensor([ 0.2621,  0.8453, -0.6630], requires_grad=True)
tensor([2.2621, 2.8453, 1.3370], grad_fn=<AddBackward0>)
tensor(10.0002, grad_fn=<MeanBackward0>)
tensor([3.0161, 3.7937, 1.7827])
