### Import module

In [2]:
import torch

### Gradient

In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x+2
z = y*y*2
z = z.mean()  # loss function
print(z)

z.backward()  # 自動計算 z 對於所有 requires_grad=True 的變數的梯度 dz/dx
print(x.grad)

tensor([-1.3660,  1.4051,  0.8434], requires_grad=True)
tensor(13.3876, grad_fn=<MeanBackward0>)
tensor([0.8453, 4.5401, 3.7912])


### Parameter updates that without involve the model (remove gradient_fn)

In [4]:
x = torch.randn(3, requires_grad=True)
print(x)

# 1.
# x.requires_grad_(False)
# print(x)

# 2.
# y = x.detach()
# print(y)

# 3.
with torch.no_grad():
    y = x+2
    print(y)

tensor([-0.3744, -0.2508,  0.4201], requires_grad=True)
tensor([1.6256, 1.7492, 2.4201])


In [5]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)
    
    #以便在下一個 epoch 中重新計算新的梯度。這是因為 PyTorch 默認會將計算的梯度累加在一起，所以在每個 epoch 開始之前，我們需要將梯度歸零。
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


### 一個能快速計算Gradient的algo
快速的算出 ∂C/∂w 與 ∂C/∂b。有了 ∂C/∂w 與 ∂C/∂b，我們就能夠知道當 Weight (w) 與 Bias (b) 變化時，Cost Function 的數值會增加還是減少，增加多少以及減少多少。

In [6]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0,requires_grad=True)

y_hat = w * x
loss = (y_hat - y)**2

print(loss)

loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
