### Import module

In [1]:
import torch
import numpy as np

### Create tensor (Pytorch only know tensor)

In [2]:
x = torch.rand(4, 4)
y = torch.rand(4, 4)
x = torch.zeros(2, 2)
x = torch.ones(2, 2, dtype=torch.float16)
x = torch.tensor([2.4, 0.1])

### Calculate, if doing in-place calculation need add _

In [3]:
x = torch.rand(4, 4)
y = torch.rand(4, 4)
y.add_(x)
y.sub_(x)
y.mul_(x)
z = torch.add(x, y)
z = torch.sub(x, y)
z = torch.mul(x, y)
print(x)

tensor([[0.8395, 0.3262, 0.4077, 0.7114],
        [0.2979, 0.3172, 0.3537, 0.3387],
        [0.0101, 0.9743, 0.6199, 0.7991],
        [0.5694, 0.1597, 0.8542, 0.2505]])


### Get tensor value

In [4]:
x = torch.rand(3, 5)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1, 1].item())  # get actual value

tensor([[0.9987, 0.5712, 0.9185, 0.7364, 0.5999],
        [0.1873, 0.5901, 0.3172, 0.1576, 0.0211],
        [0.2053, 0.8956, 0.0394, 0.8946, 0.2389]])
tensor([0.9987, 0.1873, 0.2053])
tensor([0.1873, 0.5901, 0.3172, 0.1576, 0.0211])
0.5901265740394592


### Tensor operate

In [5]:
x = torch.rand(4, 4)
y = torch.rand(4, 4)
y = x.view(16)
y = x.view(-1, 8)  # auto*8
print(y.size())

torch.Size([2, 8])


### torch -> numpy

In [6]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b, type(b))
a.add_(1) # if we run in CPU then a and b will run in the same memory place
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### numpy -> torch

In [7]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
a += 1  # if we run in CPU then a and b will run in the same memory place
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### run in GPU（MAC need to use in the other way）

In [9]:
# Torch -> tensor -> GPU
# Numpy -> array -> CPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    # z.numpy()  # would be error, numpy can't be used in GPU
    z = z.to("cpu")