# 7 章コラム　 Numpy を使ったコーディングテクニック


In [1]:
import numpy as np

## ベクトル・ベクトル間の内積


In [2]:
# w = (1, 2)
w = np.array([1, 2])
print(w)
print(w.shape)

[1 2]
(2,)


In [3]:
# x = (3, 4)
x = np.array([3, 4])
print(x)
print(x.shape)

[3 4]
(2,)


In [4]:
# (3.7.2)式の内積の実装例
# y = 1*3 + 2*4 = 11
y = x @ w
print(y)

11


## 行列・ベクトル間の内積


In [5]:
# X は3行2列の行列
X = np.array([[1, 2], [3, 4], [5, 6]])
print(X)
print(X.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [6]:
Y = X @ w
print(Y)
print(Y.shape)

[ 5 11 17]
(3,)


## データ系列方向の行列・ベクトル間の内積


In [7]:
# 転置行列の作成
XT = X . T
print(X)
print(XT)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [8]:
yd = np.array([1, 2, 3])
print(yd)

[1 2 3]


In [9]:
# 勾配値の計算(の一部)
grad = XT @ yd
print(grad)

[22 28]
